title: KISS
description: Documentation for the KISS Project
#baseurl: "/online-docs"
#url: "https://yolij.github.io

# Pin the Just the Docs version
remote_theme: just-the-docs/just-the-docs@v0.4.0.rc1
#remote_theme: just-the-docs/just-the-docs@v0.3.3

# Aux links for the upper right navigation
aux_links:
"The KISS prototype on GitHub (private)":
    - "//github.com/Deltares/KissProto1"

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: true    

# Set a path/url to a logo that will be displayed instead of the title
logo: "/assets/images/kissprojectavatar.png"

# Custom colour scheme
color_scheme: deltares