title: KISS
description: Documentation for the KISS Project
baseurl: "/online-docs" # the subpath of your site, e.g. /blog
url: "https://yolij.github.io # the base hostname & protocol for your site, e.g. http://example.com

# Pin the Just the Docs version
remote_theme: just-the-docs/just-the-docs@v0.4.0.rc1
#remote_theme: just-the-docs/just-the-docs@v0.3.3

# Aux links for the upper right navigation
aux_links:
"The KISS prototype on GitHub (private)":
    - "//github.com/Deltares/KissProto1"

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: true    

# External navigation links
nav_external_links:
  - title: The KISS prototype on GitHub (private)
    url: https://github.com/Deltares/KissProto1

# Set a path/url to a logo that will be displayed instead of the title
logo: "/assets/images/kissprojectavatar.png"

# Custom colour scheme
color_scheme: deltares